### ISSUE TITLE
documentation spawned in another dimension maybe

### ISSUE THREAD

**Issue by superon** [ThebigTijn/RandomSpawn#1]
no clue how to get this do work as per the modrinth description re: "spawn players in a random location everytime they die or join the first time" i'm particularly interested in the "join first time" part of the description but i guess that doesn't matter as it didn't generate a config file, i've have yet to discover randomspawn commands, it doesn't appear to be datapack driven and there's nothing tangible on github either so really in the dark about the whole process i'm supposed to be following with this.
:/ fabric 1.20.1

**Comment by ThebigTijn** [comment]
Did the config not generate? That is interesting, are there any errors?

**Comment by superon** [comment]
no config, no errors

**Comment by superon** [comment]
> Did the config not generate? That is interesting, are there any errors?

what is the config supposed to look like, maybe if you posted it i could check on that? also what version of fabric modloader should i use i it's particular?

**Comment by superon** [comment]
[latest.log](https://github.com/user-attachments/files/17089906/latest.log)

**Comment by ThebigTijn** [comment]
Are you trying to load it on client or server?

**Comment by superon** [comment]
client... thought this info would be in the log

**Comment by ThebigTijn** [comment]
On the modrinth page it says it only works serverside.

**Comment by superon** [comment]
o dang... could i turn this issue into a suggestion:   make client option for 0.1.2?  thanks
